name: curl_parser
description: Parse cURL command to Dart object and convert Dart object to cURL commands.
version: 0.1.0
repository: https://github.com/foss42/apidash/tree/main/packages/curl_parser

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  args: ">=2.3.1 <3.0.0"
  equatable: ^2.0.5
  shlex: ^2.0.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.0
