name: apidash
description: API Dash is a beautiful open-source cross-platform API Client built using Flutter which can help you easily create & customize your API requests, visually inspect responses and generate Dart code on the go.
version: 0.3.0+1
homepage: https://github.com/yourusername/apidash

environment:
  sdk: '>=2.19.2 <3.0.0'
  flutter: '>=3.7.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  multi_split_view: ^2.4.1
  url_launcher: ^6.1.10
  flutter_riverpod: ^1.0.0
  uuid: ^3.0.7
  davi: ^3.2.0
  http: ^0.13.5
  http_parser: ^4.0.2
  collection: ^1.17.0
  google_fonts: ^2.1.0
  highlighter: ^0.2.0
  xml: ^5.5.0
  jinja: ^0.4.2
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
  hive_flutter: ^2.0.4
  lottie: ^2.3.3
  mime: ^1.0.0
  path_provider: ^2.0.14
  window_manager: ^0.3.2
  path: ^1.8.2
  flutter_markdown: ^1.1.0
  markdown: ^5.0.2
  just_audio: ^0.11.1
  just_audio_mpv: ^0.1.6
  just_audio_windows: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2
  test: ^1.19.0

flutter:
  uses-material-design: true
  assets:
    - google_fonts/
    - assets/
    - assets/intro/
  platforms:
    windows:
      pluginClass: WindowManagerPlugin
