name: apidash
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  multi_split_view: ^2.4.0
  desktop_window: ^0.4.0
  flutter_riverpod: ^2.1.3
  uuid: ^3.0.7
  davi: ^3.2.0
  http: ^0.13.5
  collection: ^1.17.0
  flutter_json_view: ^1.0.0
  google_fonts: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
