name: postman
description: Seamlessly work with postman collections
version: 0.0.1-dev.1
homepage: https://github.com/foss42/apidash

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
