name: postman
description: Seamlessly work with postman collections
version: 0.0.1-dev.2
homepage: https://github.com/foss42/apidash

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  freezed_annotation: ^2.4.4

dev_dependencies:
  build_runner: ^2.4.12
  freezed: ^2.5.7
  json_serializable: ^6.7.1
  lints: ^4.0.0
  test: ^1.24.0
